### ISSUE TITLE
Backport to Fabric 1.20.1

### ISSUE THREAD

**Issue by ChandelureF-5** [falkreon/ConventionalCubes#1]
I understand this might not be something you wish to pursue, but players who like Fabric 1.20.1(or wish to play with mods that virtually require it) would likely love to have this mod in their worlds.

**Comment by falkreon** [comment]
I will not be porting the 1.20.1 version to Fabric, as 0.8.2 will already run happily alongside Fabric mods (via quilt), and because as a rule I don't do backports.
